services:
  llm_aug_container:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build:
      context: .
      args:
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
        SERVICE_ACC_NAME: ${SERVICE_ACC_NAME}
        SERVICE_ACC_UID: ${SERVICE_ACC_UID}
        GROUP_NAME: ${GROUP_NAME}
        GROUP_ID: ${GROUP_ID}
        REGISTRY: ${RELEASE_REGISTRY}
    working_dir: /home/${USER_NAME}/src
    stdin_open: true
    tty: true
    environment:
      http_proxy: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}
      GROUP_ID: ${GROUP_ID}
      GROUP_NAME: ${GROUP_NAME}
      USER_ID: ${USER_ID}
      USER_NAME: ${USER_NAME}

    # Uncomment below to add your user and mount sandbox home dir when you run the container

    # user: root:0
    # entrypoint: ['/entrypoint.sh']

    volumes:
      - ${DATA_PATH}:/data
      - ${SRC_PATH}:/src


