name: 🏗️ Build and store
run-name: 🏗️ Build and store version ${{ (github.event_name == 'push' || github.event_name == 'release') && github.ref_name || github.sha }}

on:
  release:
    types:
      - prereleased
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ (github.event_name == 'push' || github.event_name == 'release') && github.ref_name || github.sha }}

jobs:
  build:
    name: 🏗️ Build the image
    runs-on: [cvlab-ci]
    env:
      # Use the mirror with http (registry in the "FROM" instruction)
      SNAPSHOT_REGISTRY: ${{ vars.SF2_REGISTRY_URL }}/${{ vars.SF2_DOCKER_SNAPSHOT }}
      RELEASE_REGISTRY: ${{ vars.SF2_REGISTRY_URL }}/${{ vars.SF2_DOCKER_RELEASE }}
      NEWUSERS_FILE_PATH: ./src/controlnet_sdxl/new_users.txt
    steps:
      - name: 📁 Checkout
        uses: actions/checkout@v3

      # 🚨 IF YOU NEED TO CHANGE THE IMAGE NAME, PLEASE UPDATE THIS STEP
      - name: 🎫 Get image name from repo name
        id: get-image-name
        uses: GLB-BDS-AILAB-CV/tools-shared_workflows/.github/actions/get-name@v0.3
        with:
          snapshot-registry: ${{ env.SNAPSHOT_REGISTRY }}

      # We need to login first to access artifactory at build time
      - name: 🔐 Login to Artifactory
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.SF2_REGISTRY_URL }}
          username: ${{ secrets.GLB_BDS_SF2_JFROG_USERNAME }}
          password: ${{ secrets.GLB_BDS_SF2_JFROG_PWD }}

      - name: 🎫 Get a file with all users to add
        run: printf "${{ secrets.NEWUSERS_CVLAB }}" > "${{ env.NEWUSERS_FILE_PATH }}"
      - name: 🎫 Get a file with all users to add (verification)
        run: cat ${{ env.NEWUSERS_FILE_PATH }}

      - name: 🏗️ Build the image
        id: build
        env:
          # Variables needed in docker compose
          HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
          HTTPS_PROXY: ${{ secrets.HTTP_PROXY }}
          GROUP_ID: ${{ vars.SERVICE_ACC_GROUP_ID }}
          GROUP_NAME: ${{ vars.SERVICE_ACC_GROUP_NAME }}
          SERVICE_ACC_UID: ${{ vars.SERVICE_ACC_UID }}
          SERVICE_ACC_NAME: ${{ vars.SERVICE_ACC_NAME }}
          LOW_SHM: ${{ secrets.LOW_SHM }}
          HIGH_SHM: ${{ secrets.HIGH_SHM }}
          SRC_PATH: ${{ secrets.SRC_PATH }}
          MY_USER_ID: ${{ secrets.MY_USER_ID }}
          MY_ACC_NAME: ${{ secrets.MY_ACC_NAME }}
          NEWUSERS_FILE_PATH: ./src/controlnet_sdxl/new_users.txt

          # 🚨 IF YOU NEED MORE ENVIRONMENT VARIABLES AT BUILD, PLEASE ADD THEM HERE

          # Tag depends on the trigger that called this workflow [ manual | merge | release ]
          #   manual  ->  <image-name>:<ref-hash>
          #   merge   ->  <image-name>:<ref-name>
          #   release ->  <image-name>:<tag>
          IMAGE_NAME_CONTROLNET: ${{ steps.get-image-name.outputs.snapshot-name }}/controlnet
          IMAGE_TAG_CONTROLNET: ${{ env.IMAGE_TAG }}
          IMAGE_NAME_BASELINE: ${{ steps.get-image-name.outputs.snapshot-name }}/baseline
          IMAGE_TAG_BASELINE: ${{ env.IMAGE_TAG }}
          IMAGE_NAME_BLIP: ${{ steps.get-image-name.outputs.snapshot-name }}/blip
          IMAGE_TAG_BLIP: ${{ env.IMAGE_TAG }}
          IMAGE_NAME_MLFLOW: ${{ steps.get-image-name.outputs.snapshot-name }}/mlflow
          IMAGE_TAG_MLFLOW: ${{ env.IMAGE_TAG }}
          IMAGE_NAME_DEEPF: ${{ steps.get-image-name.outputs.snapshot-name }}/deepfloyd
          IMAGE_TAG_DEEPF: ${{ env.IMAGE_TAG }}
          IMAGE_NAME_SDXL: ${{ steps.get-image-name.outputs.snapshot-name }}/sdxl
          IMAGE_TAG_SDXL: ${{ env.IMAGE_TAG }}
          IMAGE_NAME_EVAL: ${{ steps.get-image-name.outputs.snapshot-name }}/eval
          IMAGE_TAG_EVAL: ${{ env.IMAGE_TAG }}
          IMAGE_NAME: ${{ steps.get-image-name.outputs.snapshot-name }}

          # Use legacy builder
          DOCKER_BUILDKIT: '0'

        # With no-cache because of pip dependencies
        run: docker compose build

      - name: 📦 Store the baseline model image
        run: docker push ${{ steps.get-image-name.outputs.snapshot-name }}/baseline:${{ env.IMAGE_TAG }}

      - name: 📦 Store the controlnet finetuning image
        run: docker push ${{ steps.get-image-name.outputs.snapshot-name }}/controlnet:${{ env.IMAGE_TAG }}

      - name: 📦 Store the blip image
        run: docker push ${{ steps.get-image-name.outputs.snapshot-name }}/blip:${{ env.IMAGE_TAG }}

      - name: 📦 Store the mlflow image
        run: docker push ${{ steps.get-image-name.outputs.snapshot-name }}/mlflow:${{ env.IMAGE_TAG }}

      - name: 📦 Store the deepfloyd image
        run: docker push ${{ steps.get-image-name.outputs.snapshot-name }}/deepfloyd:${{ env.IMAGE_TAG }}

      - name: 📦 Store the sdxl image
        run: docker push ${{ steps.get-image-name.outputs.snapshot-name }}/sdxl:${{ env.IMAGE_TAG }}

      - name: 📦 Store the model evaluation image
        run: docker push ${{ steps.get-image-name.outputs.snapshot-name }}/eval:${{ env.IMAGE_TAG }}

      - name: 📜 Summary
        run: |
          echo "### \`${{ steps.get-image-name.outputs.name }}\` built and published" >> "$GITHUB_STEP_SUMMARY"
          echo "To use it you can run: \`docker pull ${{ steps.get-image-name.outputs.snapshot-name }}:${{ env.IMAGE_TAG }}\`" >> "$GITHUB_STEP_SUMMARY"
