name: 🏗️ Build and store
run-name: 🏗️ Build and store version ${{ (github.event_name == 'push' || github.event_name == 'release') && github.ref_name || github.sha }}

on:
  release:
    types:
      - prereleased
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ (github.event_name == 'push' || github.event_name == 'release') && github.ref_name || github.sha }}
  REPO_URL: https://github.com/${{ github.repository }}
jobs:
  build:
    name: 🏗️ Build the image
    runs-on: large-runner-ubuntu
    steps:
      - name: 🔒 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🎫 Get image name
        id: get-image-name
        run: |
          echo "name=ghcr.io/${{ github.repository_owner }}/${{ vars.IMAGE_NAME }}" >> "$GITHUB_OUTPUT"

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🚀 Build & push baseline image
        uses: docker/bake-action@v6
        env:
          # Tag depends on the trigger that called this workflow [ manual | merge | release ]
          #   manual  ->  <image-name>:<ref-hash>
          #   merge   ->  <image-name>:<ref-name>
          #   release ->  <image-name>:<tag>
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          IMAGE_NAME_BASELINE: ${{ steps.get-image-name.outputs.name }}/baseline
        with:
          source: .
          push: true
          # Only build/push the 'baseline_model' target
          targets: baseline_model
          set: |
            *.tags=ghcr.io/${{ github.repository_owner }}/${{ vars.IMAGE_NAME }}/baseline:${{ github.sha }}

      - name: 📜 Summary
        run: |
          echo "### \`${{ steps.get-image-name.outputs.name }}/baseline:${{ env.IMAGE_TAG }}\` built and published" >> "$GITHUB_STEP_SUMMARY"
          echo "Pull with: \`docker pull ${{ steps.get-image-name.outputs.name }}/baseline:${{ env.IMAGE_TAG }}\`" >> "$GITHUB_STEP_SUMMARY"

      # - name: 📦 Store the controlnet finetuning image
      #   run: docker push ${{ steps.get-image-name.outputs.name }}/controlnet:${{ env.IMAGE_TAG }}

      # - name: 📦 Store the blip image
      #   run: docker push ${{ steps.get-image-name.outputs.name }}/blip:${{ env.IMAGE_TAG }}

      # - name: 📦 Store the mlflow image
      #   run: docker push ${{ steps.get-image-name.outputs.name }}/mlflow:${{ env.IMAGE_TAG }}

      # - name: 📦 Store the deepfloyd image
      #   run: docker push ${{ steps.get-image-name.outputs.name }}/deepfloyd:${{ env.IMAGE_TAG }}

      # - name: 📦 Store the sdxl image
      #   run: docker push ${{ steps.get-image-name.outputs.name }}/sdxl:${{ env.IMAGE_TAG }}

      # - name: 📦 Store the model evaluation image
      #   run: docker push ${{ steps.get-image-name.outputs.name }}/eval:${{ env.IMAGE_TAG }}

      # - name: 📦 Store the cyclegan turbo image
      #   run: docker push ${{ steps.get-image-name.outputs.name }}/gan:${{ env.IMAGE_TAG }}
